<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mokshi" failures="2" tests="6" name="testng.aseert" time="0.018" errors="0" timestamp="2024-08-28T02:09:11 CDT" skipped="0">
  <testcase classname="testng.aseert" name="s5" time="0.002">
    <system-out>
      <![CDATA[s5test started
s5test passed]]>
    </system-out>
  </testcase> <!-- s5 -->
  <testcase classname="testng.aseert" name="s6" time="0.001">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testng.aseert.s6(aseert.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[s6test started
s6test fialed]]>
    </system-out>
  </testcase> <!-- s6 -->
  <testcase classname="testng.aseert" name="s3" time="0.002">
    <system-out>
      <![CDATA[s3test started
s3test passed]]>
    </system-out>
  </testcase> <!-- s3 -->
  <testcase classname="testng.aseert" name="s1" time="0.009">
    <system-out>
      <![CDATA[s1test started
s1test passed]]>
    </system-out>
  </testcase> <!-- s1 -->
  <testcase classname="testng.aseert" name="s2" time="0.002">
    <system-out>
      <![CDATA[s2test started
s2test passed]]>
    </system-out>
  </testcase> <!-- s2 -->
  <testcase classname="testng.aseert" name="s4" time="0.002">
    <failure message="The following asserts failed:
	expected [Hell] but found [Hello],
	expected [null] but found [Hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Hell] but found [Hello],
expected [null] but found [Hello]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testng.aseert.s4(aseert.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[s4test started
this test s4 shoould fail as it is not null
s4test fialed]]>
    </system-out>
  </testcase> <!-- s4 -->
  <system-out>
    <![CDATA[beforesuite method
execution started
beforeclass method
beforemethod method
firsttesttest started
first testcase running
firsttesttest passed
firsttestpassed
aftermethod method
beforemethod method
secondtesttest started
second testcase running
secondtesttest passed
secondtestpassed
aftermethod method
afterclass method
s1test started
s1test passed
s2test started
s2test passed
s3test started
s3test passed
s4test started
this test s4 shoould fail as it is not null
s4test fialed
s5test started
s5test passed
s6test started
s6test fialed
dataprovidertest started
admin
password
dataprovidertest passed
forgottest fialed
s2test started
s2 is reunning
s2test fialed
test failed ats2
s3test started
s2 is reunning
s3test passed
test passed ats3
paramtest fialed
s1test started
first smoke test 
s1test passed
s2test started
first smoke test 
s2test passed
s3test started
first smoke test 
s3test passed
tc4test started
tc4 is running
tc4test passed
tc4test started
tc4 is running
tc4test passed
tc4test started
tc4 is running
tc4test passed
tc2test started
tc2 is running
tc2test passed
tc3test started
tc3test passed
tc5test started
tc5 is running
tc5test passed
tc1test started
tc1 is running
tc1test passed
execution finished
aftersuite method]]>
  </system-out>
</testsuite> <!-- testng.aseert -->
